# Generated by Django 4.0.5 on 2022-06-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numberPlate', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(null=True, upload_to='media')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
